/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/presentation/components/common/control/BaseButton/index.vue')['default']
    BaseLink: typeof import('./src/presentation/components/common/typography/BaseLink/index.vue')['default']
    CartLink: typeof import('./src/presentation/components/layout/Header/CartLink/index.vue')['default']
    Categories: typeof import('./src/presentation/components/page/Home/Categories/index.vue')['default']
    CategoryCart: typeof import('./src/presentation/components/feature/CategoryCart/index.vue')['default']
    Footer: typeof import('./src/presentation/components/layout/Footer/index.vue')['default']
    Header: typeof import('./src/presentation/components/layout/Header/index.vue')['default']
    Home: typeof import('./src/presentation/components/page/Home/index.vue')['default']
    Intro: typeof import('./src/presentation/components/page/Home/Intro/index.vue')['default']
    Layout: typeof import('./src/presentation/components/layout/Layout/index.vue')['default']
    Loader: typeof import('./src/presentation/components/common/block/Loader/index.vue')['default']
    Navbar: typeof import('./src/presentation/components/layout/Header/Navbar/index.vue')['default']
    NotFound: typeof import('./src/presentation/components/page/NotFound/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
