/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToCartButton: typeof import('./src/presentation/components/feature/AddToCartButton/index.vue')['default']
    BaseButton: typeof import('./src/presentation/components/common/control/BaseButton/index.vue')['default']
    BaseFooter: typeof import('./src/presentation/components/layout/BaseFooter/index.vue')['default']
    BaseHeader: typeof import('./src/presentation/components/layout/BaseHeader/index.vue')['default']
    BaseLayout: typeof import('./src/presentation/components/layout/BaseLayout/index.vue')['default']
    BaseLink: typeof import('./src/presentation/components/common/typography/BaseLink/index.vue')['default']
    BaseLoader: typeof import('./src/presentation/components/common/block/BaseLoader/index.vue')['default']
    CardContainer: typeof import('./src/presentation/components/feature/CardContainer/index.vue')['default']
    CardImage: typeof import('./src/presentation/components/common/block/CardImage/index.vue')['default']
    CartItem: typeof import('./src/presentation/components/page/CartPage/CartItem/index.vue')['default']
    CartLink: typeof import('./src/presentation/components/layout/BaseHeader/CartLink/index.vue')['default']
    CartPage: typeof import('./src/presentation/components/page/CartPage/index.vue')['default']
    CategoriesBlock: typeof import('./src/presentation/components/page/HomePage/CategoriesBlock/index.vue')['default']
    CategoryCard: typeof import('./src/presentation/components/feature/CategoryCard/index.vue')['default']
    CategoryView: typeof import('./src/presentation/components/page/ProductsPage/CategoryView/index.vue')['default']
    EmptyBlock: typeof import('./src/presentation/components/feature/EmptyBlock/index.vue')['default']
    ErrorPage: typeof import('./src/presentation/components/page/ErrorPage/index.vue')['default']
    HeaderNavbar: typeof import('./src/presentation/components/layout/BaseHeader/HeaderNavbar/index.vue')['default']
    HomePage: typeof import('./src/presentation/components/page/HomePage/index.vue')['default']
    ImageCarousel: typeof import('./src/presentation/components/common/block/ImageCarousel/index.vue')['default']
    IntroBlock: typeof import('./src/presentation/components/page/HomePage/IntroBlock/index.vue')['default']
    ProductCard: typeof import('./src/presentation/components/feature/ProductCard/index.vue')['default']
    ProductList: typeof import('./src/presentation/components/page/ProductsPage/CategoryView/ProductList/index.vue')['default']
    ProductsBlock: typeof import('./src/presentation/components/page/HomePage/ProductsBlock/index.vue')['default']
    ProductsPage: typeof import('./src/presentation/components/page/ProductsPage/index.vue')['default']
    ProductView: typeof import('./src/presentation/components/page/ProductsPage/ProductView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubcategoriesList: typeof import('./src/presentation/components/page/ProductsPage/CategoryView/SubcategoriesList/index.vue')['default']
  }
}
