/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToCartButton: typeof import('./src/presentation/components/feature/AddToCartButton/index.vue')['default']
    BaseButton: typeof import('./src/presentation/components/common/control/BaseButton/index.vue')['default']
    BaseLink: typeof import('./src/presentation/components/common/typography/BaseLink/index.vue')['default']
    CardContainer: typeof import('./src/presentation/components/feature/CardContainer/index.vue')['default']
    CardImage: typeof import('./src/presentation/components/common/block/CardImage/index.vue')['default']
    Carousel: typeof import('./src/presentation/components/common/block/Carousel/index.vue')['default']
    Cart: typeof import('./src/presentation/components/page/Cart/index.vue')['default']
    CartItem: typeof import('./src/presentation/components/page/Cart/CartItem/index.vue')['default']
    CartLink: typeof import('./src/presentation/components/layout/Header/CartLink/index.vue')['default']
    CategoriesBlock: typeof import('./src/presentation/components/page/Home/CategoriesBlock/index.vue')['default']
    Category: typeof import('./src/presentation/components/page/Products/Category/index.vue')['default']
    CategoryCard: typeof import('./src/presentation/components/feature/CategoryCard/index.vue')['default']
    EmptyBlock: typeof import('./src/presentation/components/feature/EmptyBlock/index.vue')['default']
    EmptyCategory: typeof import('./src/presentation/components/page/Products/Category/EmptyCategory/index.vue')['default']
    ErrorPage: typeof import('./src/presentation/components/page/ErrorPage/index.vue')['default']
    Footer: typeof import('./src/presentation/components/layout/Footer/index.vue')['default']
    Header: typeof import('./src/presentation/components/layout/Header/index.vue')['default']
    Home: typeof import('./src/presentation/components/page/Home/index.vue')['default']
    Intro: typeof import('./src/presentation/components/page/Home/Intro/index.vue')['default']
    Layout: typeof import('./src/presentation/components/layout/Layout/index.vue')['default']
    Loader: typeof import('./src/presentation/components/common/block/Loader/index.vue')['default']
    Navbar: typeof import('./src/presentation/components/layout/Header/Navbar/index.vue')['default']
    Product: typeof import('./src/presentation/components/page/Products/Product/index.vue')['default']
    ProductCard: typeof import('./src/presentation/components/feature/ProductCard/index.vue')['default']
    ProductList: typeof import('./src/presentation/components/page/Products/Category/ProductList/index.vue')['default']
    Products: typeof import('./src/presentation/components/page/Products/index.vue')['default']
    ProductsBlock: typeof import('./src/presentation/components/page/Home/ProductsBlock/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subcategories: typeof import('./src/presentation/components/page/Products/Category/Subcategories/index.vue')['default']
  }
}
